default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: true) # Handles signing
    build_app(scheme: "PlannerBot") # Build the app
    upload_to_testflight # Upload to TestFlight
  end
end
