default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "PlannerBot.xcodeproj")

    build_app(
      workspace: "PlannerBot.xcworkspace",
      scheme: "PlannerBot",
      configuration: "Release"
    )

    upload_to_testflight
  end
end
