name: Deploy to Internal Testing

on:
  push:
    branches:
      - main

jobs:
#  android:
#    name: Build and Upload Android APK/AAB
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Set up JDK
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: '17'
#
#      - name: Install dependencies
#        run: |
#          npm install
#          cd android && ./gradlew dependencies
#
#      - name: Decode Keystore
#        env:
#          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
#        run: |
#          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/my-upload-key.keystore
#
#      - name: Build Android Release
#        env:
#          SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
#          SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
#          SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
#        run: |
#          cd android
#          ./gradlew bundleRelease
#
#      - name: Upload to Google Play Internal Testing
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
#          packageName: "com.yourapp.package"
#          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
#          track: internal
#          status: completed

  ios:
    name: Build and Upload iOS to TestFlight
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Fastlane
        run: gem install fastlane

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Build and deploy to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APPLE_AUTH_KEY }}
          MATCH_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
          FASTLANE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          cd ios
          fastlane beta
